### ISSUE TITLE
Unable to connect to Windows server

### ISSUE THREAD

**Issue by sean-perryman** [jean343/RPI-GPU-rdpClient#3]
I've installed all of the prerequisites and compiled the source, but when I execute it with an IP and port number it just closes for me. Here is what I receive:

```
pi@raspberrypi ~/RPI-GPU-rdpClient/RPI-Client/build $ ./client 192.168.1.10 3389 
Version 0.9
Open display[0]...
Display is 1920 x 1080
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  write: Connection reset by peer
Aborted
```

Going to try rebooting and see if that helps, any ideas?

**Comment by jean343** [comment]
Hello,

Thanks for the interest.

Did you run the server with port 3389? The default is port 8080.
Is the port opened in your firewall? Can you ping 192.168.1.10 and telnet
192.168.1.10 3389?

Is there a message shown on your windows box running ./server monitor 0
port 3389?

Keep me posted!

**Comment by sean-perryman** [comment]
I will give it a shot tomorrow and report back. Thanks for getting back so quickly!

Sean

**Comment by jean343** [comment]
Closing as this issue is inactive.
