### ISSUE TITLE
Server does not compile in VS 2019

### ISSUE THREAD

**Issue by houstonnoproblems** [jean343/RPI-GPU-rdpClient#9]
Hey Jean,

Thanks for this, I've been looking for a GPU accelerated remote desktop solution that works with RPI.

I'm having a bit of trouble building the server in VS. I'm on Windows 10, using CMAKE 3.22.0, VS 2019, and Cuda 10.0 and Cuda 11

Upon building the solution, I am getting identifier undefined errors as well as syntax errors.

What am I doing wrong? Any help would greatly be appreciated.
![Errors1](https://user-images.githubusercontent.com/86631311/138346931-afe3d457-780c-4047-a038-50dcc81fa553.PNG)
![Errors2](https://user-images.githubusercontent.com/86631311/138346935-4b263dce-f4f5-4ac1-915f-9d1249007615.PNG)

**Comment by jean343** [comment]
Thanks for your question, I will try to get a windows machine to try it later.

This [article](https://developercommunity.visualstudio.com/t/int-winstorageapi-redefinition-in-visual-studio-20/828764) might help, let me know if it does.

**Comment by houstonnoproblems** [comment]
> 
> 
> Thanks for your question, I will try to get a windows machine to try it later.
> 
> This [article](https://developercommunity.visualstudio.com/t/int-winstorageapi-redefinition-in-visual-studio-20/828764) might help, let me know if it does.

It worked thank you!
